apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: 3-tier-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: nginx.gweowe.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
  - host: tomcat.gweowe.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tomcat-service
            port:
              number: 8080
  - host: postgresql.gweowe.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: postgresql-postgresql-ha-pgpool
            port:
              number: 5432
