apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  nfs:
    path: /home/nfs/3-tier-architecture-project/postgresql/postgresql
    server: 77.88.120.210
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:16.3
        env:
        - name: POSTGRES_DB
          value: user_database
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "gweowe123"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgresql-storage
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: postgresql-service
spec:
  type: NodePort
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 35432
